### ISSUE TITLE
Incompatible plugin

### ISSUE THREAD

**Issue by zolotov** [adelf/idea-php-dotenv-plugin#29]
Go plugin: 172.3968.45
IntelliJ IDEA 2017.2.7  Build #IU-172.4574.19

```
2018-09-21 11:14:41,996 [ 108616]  ERROR - napi.project.CacheUpdateRunner - Error while indexing ***
To reindex this file IDEA has to be restarted
java.lang.NoSuchMethodError: com.goide.psi.impl.GoPsiUtil.getCallReference(Lcom/goide/psi/GoExpression;)Lcom/goide/psi/GoReferenceExpression;
	at ru.adelf.idea.dotenv.go.GoPsiHelper.getEnvironmentGoLiteral(GoPsiHelper.java:27)
	at ru.adelf.idea.dotenv.go.GoEnvironmentCallsVisitor.visitCall(GoEnvironmentCallsVisitor.java:26)
	at ru.adelf.idea.dotenv.go.GoEnvironmentCallsVisitor.visitElement(GoEnvironmentCallsVisitor.java:19)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.goide.psi.impl.GoExpressionImpl.accept(GoExpressionImpl.java:27)
	at com.goide.psi.impl.GoCallExprImpl.accept(GoCallExprImpl.java:25)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at ru.adelf.idea.dotenv.go.GoEnvironmentCallsVisitor.visitElement(GoEnvironmentCallsVisitor.java:22)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.goide.psi.impl.GoVarSpecImpl.accept(GoVarSpecImpl.java:35)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at ru.adelf.idea.dotenv.go.GoEnvironmentCallsVisitor.visitElement(GoEnvironmentCallsVisitor.java:22)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.goide.psi.impl.GoVarDeclarationImpl.accept(GoVarDeclarationImpl.java:33)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:861)
	at ru.adelf.idea.dotenv.go.GoEnvironmentVariablesUsagesProvider.getUsages(GoEnvironmentVariablesUsagesProvider.java:25)
	at ru.adelf.idea.dotenv.indexing.DotEnvUsagesIndex.lambda$getIndexer$0(DotEnvUsagesIndex.java:34)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:271)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:214)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1618)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1554)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1513)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1501)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by adelf** [comment]
I'll remove indexing in next version.

**Comment by zolotov** [comment]
@adelf in fact, this error you should get on the compile time, not in runtime. So the point is not to set custom since-build that you didn't actually check. If you want to set 172.1 since-build, it's better to compile the plugin against 2017.2 Platform.

**Comment by adelf** [comment]
@zolotov the main problem is that I'm not a Java developer. 
IDEA plugin development is all my Java experience.
Sometims it's so hard to fight with some things. So hard to find any info.
About 2 months ago I was trying to gradlify this plugin's build and spend more than 2 hours to these 6 lines: https://github.com/adelf/idea-php-dotenv-plugin/blob/gradle/build.gradle#L29-L35
And I'm not sure that they are correct. Then I just decided to leave it...
I'll make another try this week.

The lack of information is the main barrier in IDEA development. At least plugin's guide was a bit improved not a long time ago.
I know
https://www.jetbrains.org/intellij/sdk/docs/welcome.html
and 
https://intellij-support.jetbrains.com/hc/en-us/community/topics/200366979-IntelliJ-IDEA-Open-API-and-Plugin-Development
and some open sources in github or upsource.
If you have any other sources of info, please share :)

**Comment by zolotov** [comment]
> And I'm not sure that they are correct. Then I just decided to leave it...

Plugins statement looks good to me. The actual problem is here:

```
patchPluginXml {
    sinceBuild '172'
}
```

You declare that the plugin works in all IDEs starting from 2017.2. But:
1. This is not true
2. You cannot know that it's not true, because the plugin is built against Go-182.*, not against Go-172.* (which doesn't exist, btw), so you won't even see the compilation errors.

The only needed page here is https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html?search=build

Documentation for the `gradle-intellij-plugin` might be useful too: https://github.com/jetbrains/gradle-intellij-plugin

For the rest, I can answer your questions regarding IntelliJ plugins development.
