### ISSUE TITLE
Error while indexing

### ISSUE THREAD

**Issue by cenziano** [adelf/idea-php-dotenv-plugin#7]
After update PhpStorm from 2017.1 to 2017.2, when I restart the Ide during the indexing I recieved this error:
Error while indexing ...[phpstorm-project].../.dockers/xenialdock/Dockerfile

Details:
Error while indexing ...[phpstorm-project].../.dockers/xenialdock/Dockerfile
To reindex this file IDEA has to be restarted: com.intellij.plugins.docker.dockerFile.parser.psi.DockerFileEnvRegularDeclaration.getEnvRegularValue()Lcom/intellij/plugins/docker/dockerFile/parser/psi/DockerFileEnvRegularValue;
java.lang.NoSuchMethodError: com.intellij.plugins.docker.dockerFile.parser.psi.DockerFileEnvRegularDeclaration.getEnvRegularValue()Lcom/intellij/plugins/docker/dockerFile/parser/psi/DockerFileEnvRegularValue;
	at ru.adelf.idea.dotenv.docker.DockerfilePsiElementsVisitor.visitProperty(DockerfilePsiElementsVisitor.java:30)
	at ru.adelf.idea.dotenv.docker.DockerfilePsiElementsVisitor.visitElement(DockerfilePsiElementsVisitor.java:22)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.plugins.docker.dockerFile.parser.impl.DockerFileEnvRegularDeclarationImpl.accept(DockerFileEnvRegularDeclarationImpl.java:26)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at ru.adelf.idea.dotenv.docker.DockerfilePsiElementsVisitor.visitElement(DockerfilePsiElementsVisitor.java:25)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.plugins.docker.dockerFile.parser.impl.DockerFileEnvCommandImpl.accept(DockerFileEnvCommandImpl.java:26)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:857)
	at ru.adelf.idea.dotenv.docker.DockerfileVariablesProvider.getElements(DockerfileVariablesProvider.java:29)
	at ru.adelf.idea.dotenv.indexing.EnvironmentVariablesIndex.lambda$getIndexer$0(EnvironmentVariablesIndex.java:27)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by adelf** [comment]
Seems they changed docker API... I'll fix, thanks.

**Comment by adelf** [comment]
Github implemented autoclosing :)
I uploaded 0.4 version. After JetBrains approval(max 2 days) it will be available to update.

**Comment by cenziano** [comment]
Thanks a lot!
