### ISSUE TITLE
Plugin not working after update

### ISSUE THREAD

**Issue by HeinerTholen** [adelf/idea-php-dotenv-plugin#82]
I just updated PyCharm to 2021.2, Build #PY-212.4746.96, and the .env plugin doesn't work anymore.

I uninstalled the plugin, restarted PyCharm, installed the plugin again, restarted again. 

The ".env" tab in the Window "Run/Debug Configurations" does not appear.

**Comment by meneses-pt** [comment]
I can confirm that this is happening to me as well.

**Comment by adelf** [comment]
I suppose you're writing about another plugin - https://plugins.jetbrains.com/plugin/7861-envfile?

**Comment by meneses-pt** [comment]
Hmm, I guess you're right. I'm sorry.

**Comment by HeinerTholen** [comment]
Ouch. Sorry!

**Comment by adelf** [comment]
No problem. Please don't close this issue. A lot of people think that it's my feature...

**Comment by dcram** [comment]
![image](https://user-images.githubusercontent.com/12859843/127488577-c24bf668-0e57-4c3b-86c9-d1adb5da7a80.png)

@adelf I can confirm that I am using your plugin and that I also have my Env tab disappeared after upgrade.

By the way, thanks a lot for the great plugin. It is so useful to me that I now feel naked without it :+1: 

Damien

**Comment by adelf** [comment]
@dcram, Env tab is a feature of the "EnvFile" plugin - https://plugins.jetbrains.com/plugin/7861-envfile

**Comment by dcram** [comment]
You right @adelf. Sorry for the pollution.

**Comment by MarioPerini** [comment]
i get an "incompatible" message in PHPStorm:
![image](https://user-images.githubusercontent.com/40631006/127545560-752b4503-dd94-42a6-bb8d-2a7b93ccf802.png)

**Comment by ginkcode** [comment]
I believe the issue belongs to this plugin, because I don't install EnvFile.
<img width="1125" alt="Screen Shot 2021-07-30 at 9 33 28 AM" src="https://user-images.githubusercontent.com/9301098/127591269-9a1b9be9-eb44-404f-a7e6-ee88d3f41c2c.png">

**Comment by maddencs** [comment]
My problem is also with this plugin. I'm getting the same error as ginkcode.

**Comment by pikachujeff** [comment]
> I believe the issue belongs to this plugin, because I don't install EnvFile.
> <img alt="Screen Shot 2021-07-30 at 9 33 28 AM" width="1125" src="https://user-images.githubusercontent.com/9301098/127591269-9a1b9be9-eb44-404f-a7e6-ee88d3f41c2c.png">

I also got the same error after I update PhpStorm to 2021.2.

**Comment by x-dragos** [comment]
i'm having the same issue in PHPStorm 2021.2. just updated and :

Error while indexing C:\Users\drago\Projects\marlms\vendor\jenssegers\mongodb\Dockerfile
To reindex this file IDEA has to be restarted

java.lang.NoClassDefFoundError: com/intellij/plugins/docker/dockerFile/parser/psi/DockerFileEnvRegularDeclaration
	at ru.adelf.idea.dotenv.docker.DockerfilePsiElementsVisitor.visitElement(DockerfilePsiElementsVisitor.java:17)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.intellij.docker.dockerFile.parser.impl.DockerFileArgCommandImpl.accept(DockerFileArgCommandImpl.java:24)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:751)
	at ru.adelf.idea.dotenv.docker.DockerfileVariablesProvider.getElements(DockerfileVariablesProvider.java:27)
	at ru.adelf.idea.dotenv.indexing.DotEnvKeyValuesIndex.lambda$getIndexer$0(DotEnvKeyValuesIndex.java:35)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:328)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:318)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:182)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:47)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:263)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:232)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:55)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:26)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1520)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1394)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:638)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1361)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1315)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$5(IndexUpdateRunner.java:267)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:421)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.java:270)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$4(IndexUpdateRunner.java:210)
	at com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection(ProgressSuspender.java:83)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly(IndexUpdateRunner.java:213)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$3(IndexUpdateRunner.java:147)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.intellij.plugins.docker.dockerFile.parser.psi.DockerFileEnvRegularDeclaration PluginClassLoader(plugin=PluginDescriptor(name=.env files support, id=ru.adelf.idea.dotenv, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PhpStorm2021.2\plugins\idea-php-dotenv-plugin-2021.2.jar, version=2021.2, package=null), packagePrefix=null, instanceId=112, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 56 more

**Comment by spyridonas** [comment]
Same issue for me, i disabled the plugin for the time being.

**Comment by sorentfly** [comment]
Same, disabled too. W8 for being solved

**Comment by adelf** [comment]
What version are you using? 2021.2 or 2021.2.212?
The second one should work.

**Comment by spyridonas** [comment]
> What version are you using? 2021.2 or 2021.2.212?
> The second one should work.

I'm using 2021.2 Build PS-212.4746.100

**Comment by adelf** [comment]
I've uploaded a new version: https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/130197
Hope it will be approved soon. Thank you for all your reports.

**Comment by ginkcode** [comment]
> I've uploaded a new version: https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/130197
> Hope it will be approved soon. Thank you for all your reports.
> 
> UPD: It was approved in 2 minutes. It's a new record :)

Thank you!
Haven't seen notification for updating but reinstall will solve the problem now.

**Comment by Sammaye** [comment]
![Screenshot 2021-07-31 104126](https://user-images.githubusercontent.com/323996/127735882-0dad3ac3-0b33-4d9e-bd4c-a28db91c418e.jpg)
Even after the latest update my plugin is still saying it won't work with my version of IDE, which was super latest #PS-212.4746.100

**Comment by Sammaye** [comment]
Ah ok, nvm my post. If you uninstall it and then reinstall it works

**Comment by burstmeman** [comment]
**PhpStorm 2021.2**
Build PS-212.4746.100

```java
java.lang.NoClassDefFoundError: com/intellij/plugins/docker/dockerFile/parser/psi/DockerFileEnvRegularDeclaration
	at ru.adelf.idea.dotenv.docker.DockerfilePsiElementsVisitor.visitElement(DockerfilePsiElementsVisitor.java:17)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at com.intellij.docker.dockerFile.parser.impl.DockerFileArgCommandImpl.accept(DockerFileArgCommandImpl.java:24)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:751)
	at ru.adelf.idea.dotenv.docker.DockerfileVariablesProvider.getElements(DockerfileVariablesProvider.java:27)
	at ru.adelf.idea.dotenv.indexing.DotEnvKeyValuesIndex.lambda$getIndexer$0(DotEnvKeyValuesIndex.java:35)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:328)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:318)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:182)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:47)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:263)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:232)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:55)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:26)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1520)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$23(FileBasedIndexImpl.java:1394)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:638)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1361)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1315)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$5(IndexUpdateRunner.java:267)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:421)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:186)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.java:270)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$4(IndexUpdateRunner.java:210)
	at com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection(ProgressSuspender.java:83)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly(IndexUpdateRunner.java:213)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$3(IndexUpdateRunner.java:147)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.intellij.plugins.docker.dockerFile.parser.psi.DockerFileEnvRegularDeclaration PluginClassLoader(plugin=PluginDescriptor(name=.env files support, id=ru.adelf.idea.dotenv, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PhpStorm2021.2/plugins/idea-php-dotenv-plugin-2021.2.jar, version=2021.2, package=null), packagePrefix=null, instanceId=121, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 56 more
```

**Comment by spyridonas** [comment]
The update has fixed the issue for me,  thank you !

**Comment by IcyEagle** [comment]
Doesn't work for me as well
Plugin version - 2021.3.0.212
IDEA version - 212.4746.92

**Comment by adelf** [comment]
@IcyEagle Env tab is a feature of the "EnvFile" plugin - https://plugins.jetbrains.com/plugin/7861-envfile
